name = "SingleTrackModel"
uuid = "90ee3556-4c1f-41ac-a1cf-dff6a2ebd9e0"
authors = ["Ahmed Mogahed <a.mogahed@inginne.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
